from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class CampoContexto:
    """Campo de um registro pai repetido na aba do registro filho."""

    registro: str
    indice: int
    cabecalho: str


@dataclass(frozen=True, slots=True)
class LayoutRegistro:
    """Definição de uma aba legível do SPED."""

    codigo: str
    nome_aba: str
    cabecalhos: tuple[str, ...]
    contexto: tuple[CampoContexto, ...] = ()


# Estrutura baseada no modelo de planilha validado pela usuária na Sprint 12.3.
# O primeiro cabeçalho próprio sempre representa o REG; os demais seguem a ordem
# encontrada na linha do SPED. Campos adicionais de layouts mais novos são
# mantidos com nomes genéricos pelo exportador, sem perda de informação.
LAYOUTS_REGISTROS: dict[str, LayoutRegistro] = {
    "0000": LayoutRegistro(
        codigo="0000",
        nome_aba='0000',
        cabecalhos=('0000',
 'COD_VER',
 'COD_FIN',
 'DT_INI',
 'DT_FIN',
 'NOME',
 'CNPJ',
 'CPF',
 'UF',
 'IE',
 'COD_MUN',
 'IM',
 'SUFRAMA',
 'IND_PERFIL',
 'IND_ATIV'),
        contexto=(),
    ),
    "0001": LayoutRegistro(
        codigo="0001",
        nome_aba='0001',
        cabecalhos=('0001', 'IND_MOV'),
        contexto=(),
    ),
    "0005": LayoutRegistro(
        codigo="0005",
        nome_aba='0005',
        cabecalhos=('0005', 'FANTASIA', 'CEP', 'END', 'NUM', 'COMPL', 'BAIRRO', 'FONE', 'FAX', 'EMAIL'),
        contexto=(),
    ),
    "0100": LayoutRegistro(
        codigo="0100",
        nome_aba='0100',
        cabecalhos=('0100',
 'NOME',
 'CPF',
 'CRC',
 'CNPJ',
 'CEP',
 'END',
 'NUM',
 'COMPL',
 'BAIRRO',
 'FONE',
 'FAX',
 'EMAIL',
 'COD_MUN'),
        contexto=(),
    ),
    "0150": LayoutRegistro(
        codigo="0150",
        nome_aba='0150 - Participantes',
        cabecalhos=('0150 - Fixo',
 'Código Participante',
 'Razão Social',
 'Código País',
 'CNPJ do Participante',
 'CPF do Participante',
 'Inscrição Estadual',
 'Código Municipio',
 'Suframa',
 'Endereço',
 'Numero',
 'Complemento',
 'Bairro'),
        contexto=(),
    ),
    "0190": LayoutRegistro(
        codigo="0190",
        nome_aba='0190 - Unidades de Medidas',
        cabecalhos=('0190 - Fixo', 'Unidade de Medida', 'Descrição da Unidade de Medida'),
        contexto=(),
    ),
    "0200": LayoutRegistro(
        codigo="0200",
        nome_aba='0200 - Cadastro de Itens',
        cabecalhos=('0200 - Fixo',
 'Código do Produto/Serviços',
 'Descrição do Produto/Serviços',
 'Código de Barras',
 'Código Anterior',
 'Unidade de Medida',
 'Tipo de Item',
 'NCM',
 'EX_IPI',
 'Código do Genero',
 'Código Lista de Serviços',
 'Aliquota de ICMS',
 'CEST'),
        contexto=(),
    ),
    "0220": LayoutRegistro(
        codigo="0220",
        nome_aba='0220',
        cabecalhos=('0220', 'UNID_CONV', 'FAT_CONV', 'COD_BARRA'),
        contexto=(CampoContexto("0200", 1, 'Código do Produto/Serviços(0200)'),),
    ),
    "0400": LayoutRegistro(
        codigo="0400",
        nome_aba='0400 - Natureza de Operação',
        cabecalhos=('0400 - Fixo', 'Código da Natureza de Operação', 'Descrição da Natureza de Operação'),
        contexto=(),
    ),
    "0450": LayoutRegistro(
        codigo="0450",
        nome_aba='0450',
        cabecalhos=('0450', 'COD_INF', 'TXT'),
        contexto=(),
    ),
    "0460": LayoutRegistro(
        codigo="0460",
        nome_aba='0460',
        cabecalhos=('0460', 'COD_OBS', 'TXT'),
        contexto=(),
    ),
    "0990": LayoutRegistro(
        codigo="0990",
        nome_aba='0990',
        cabecalhos=('0990', 'QTD_LIN_0'),
        contexto=(),
    ),
    "1001": LayoutRegistro(
        codigo="1001",
        nome_aba='1001',
        cabecalhos=('1001', 'IND_MOV'),
        contexto=(),
    ),
    "1010": LayoutRegistro(
        codigo="1010",
        nome_aba='1010',
        cabecalhos=('1010',
 'IND_EXP',
 'IND_CCRF',
 'IND_COMB',
 'IND_USINA',
 'IND_VA',
 'IND_EE',
 'IND_CART',
 'IND_FORM',
 'IND_AER',
 'IND_GIAF1',
 'IND_GIAF3',
 'IND_GIAF4',
 'IND_REST_RESSARC_COMPL_ICMS'),
        contexto=(),
    ),
    "1601": LayoutRegistro(
        codigo="1601",
        nome_aba='1601',
        cabecalhos=('1601', 'COD_PART_IP', 'COD_PART_IT', 'TOT_VS', 'TOT_ISS', 'TOT_OUTROS'),
        contexto=(),
    ),
    "1900": LayoutRegistro(
        codigo="1900",
        nome_aba='1900',
        cabecalhos=('1900', 'IND_APUR_ICMS', 'DESCR_COMPL_OUT_APUR'),
        contexto=(),
    ),
    "1910": LayoutRegistro(
        codigo="1910",
        nome_aba='1910',
        cabecalhos=('1910', 'DT_INI', 'DT_FIN'),
        contexto=(CampoContexto("1900", 1, 'IND_APUR_ICMS(1900)'),),
    ),
    "1920": LayoutRegistro(
        codigo="1920",
        nome_aba='1920',
        cabecalhos=('1920',
 'VL_TOT_TRANSF_DEBITOS_OA',
 'VL_TOT_AJ_DEBITOS_OA',
 'VL_ESTORNOS_CRED_OA',
 'VL_TOT_TRANSF_CREDITOS_OA',
 'VL_TOT_AJ_CREDITOS_OA',
 'VL_ESTORNOS_DEB_OA',
 'VL_SLD_CREDOR_ANT_OA',
 'VL_SLD_APURADO_OA',
 'VL_TOT_DED',
 'VL_ICMS_RECOLHER_OA',
 'VL_SLD_CREDOR_TRANSP_OA',
 'DEB_ESP_OA'),
        contexto=(CampoContexto("1900", 1, 'IND_APUR_ICMS(1900)'),),
    ),
    "1921": LayoutRegistro(
        codigo="1921",
        nome_aba='1921',
        cabecalhos=('1921', 'COD_AJ_APUR', 'DESCR_COMPL_AJ', 'VL_AJ_APUR'),
        contexto=(CampoContexto("1900", 1, 'IND_APUR_ICMS(1900)'),),
    ),
    "1926": LayoutRegistro(
        codigo="1926",
        nome_aba='1926',
        cabecalhos=('1926', 'COD_OR', 'VL_OR', 'DT_VCTO', 'COD_REC', 'NUM_PROC', 'IND_PROC', 'PROC', 'TXT_COMPL', 'MES_REF*'),
        contexto=(CampoContexto("1900", 1, 'IND_APUR_ICMS(1900)'),),
    ),
    "1990": LayoutRegistro(
        codigo="1990",
        nome_aba='1990',
        cabecalhos=('1990', 'QTD_LIN_1'),
        contexto=(),
    ),
    "B001": LayoutRegistro(
        codigo="B001",
        nome_aba='B001',
        cabecalhos=('B001', 'IND_DAD'),
        contexto=(),
    ),
    "B990": LayoutRegistro(
        codigo="B990",
        nome_aba='B990',
        cabecalhos=('B990', 'QTD_LIN_B'),
        contexto=(),
    ),
    "C001": LayoutRegistro(
        codigo="C001",
        nome_aba='C001',
        cabecalhos=('C001', 'IND_MOV'),
        contexto=(),
    ),
    "C100": LayoutRegistro(
        codigo="C100",
        nome_aba='C100 - Nota Fiscal',
        cabecalhos=('C100 - Fixo',
 'Indicador de Operação',
 'Indicador de Emissão',
 'Participante',
 'Modelo',
 'Situação',
 'Série',
 'Numero',
 'Chave',
 'Data de Emissão',
 'Data de Entrada/Saída',
 'Valor',
 'Pagamento',
 'Desconto',
 'Abatimento',
 'Valor das Mercadorias',
 'Tipo de Frete',
 'Valor do Frete',
 'Valor do Seguro',
 'Despesas Acessórias',
 'BC de ICMS',
 'Valor de ICMS',
 'BC de ICMS ST',
 'Valor de ICMS - ST',
 'Valor de IPI',
 'Valor de Pis',
 'Valor de Cofins',
 'Valor de Pis - ST',
 'Valor de Cofins - ST'),
        contexto=(),
    ),
    "C101": LayoutRegistro(
        codigo="C101",
        nome_aba='C101',
        cabecalhos=('C101', 'VL_FCP_UF_DEST', 'VL_ICMS_UF_DEST', 'VL_ICMS_UF_REM'),
        contexto=(CampoContexto("C100", 3, 'Participante(C100)'), CampoContexto("C100", 7, 'Número da Nota(C100)'), CampoContexto("C100", 4, 'Modelo(C100)'), CampoContexto("C100", 6, 'Série(C100)'), CampoContexto("C100", 1, 'Indicador de Operação(C100)'), CampoContexto("C100", 2, 'Indicador de Emissão(C100)'),),
    ),
    "C110": LayoutRegistro(
        codigo="C110",
        nome_aba='C110',
        cabecalhos=('C110', 'COD_INF', 'TXT_COMPL'),
        contexto=(CampoContexto("C100", 3, 'Participante(C100)'), CampoContexto("C100", 7, 'Número da Nota(C100)'), CampoContexto("C100", 4, 'Modelo(C100)'), CampoContexto("C100", 6, 'Série(C100)'), CampoContexto("C100", 1, 'Indicador de Operação(C100)'), CampoContexto("C100", 2, 'Indicador de Emissão(C100)'),),
    ),
    "C170": LayoutRegistro(
        codigo="C170",
        nome_aba='C170 - Itens da Nota',
        cabecalhos=('C170 - Fixo',
 'Numeração Sequencial',
 'Código do Produto',
 'Descrição Complementar',
 'Quantidade',
 'Unidade de Medida',
 'Valor Total do Produto',
 'Valor de Desconto',
 'Movimentação Física',
 'CST de ICMS',
 'CFOP',
 'Natureza de Operação',
 'Base de Icms',
 'Alíquota de Icms',
 'Valor de Icms',
 'Base de Icms ST',
 'Alíquota de Icms ST',
 'Valor de Icms ST',
 'Indicador de Apuração de IPI',
 'CST de IPI',
 'Código Enquadramento IPI',
 'Base de IPI',
 'Alíquota de IPI',
 'Valor de IPI',
 'CST de Pis',
 'Base de Pis',
 'Alíquota de Pis',
 'Base de Pis - Qtde',
 'Alíquota de Pis Qtde',
 'Valor de Pis',
 'CST de Cofins',
 'Base de Cofins',
 'Alíquota de Cofins',
 'Base de Cofins - Qtde',
 'Alíquota de Cofins Qtde',
 'Valor de Cofins',
 'Conta Contábil',
 'Valor do abatimento não tributado'),
        contexto=(CampoContexto("C100", 3, 'Participante(C100)'), CampoContexto("C100", 7, 'Número da Nota(C100)'), CampoContexto("C100", 4, 'Modelo(C100)'), CampoContexto("C100", 6, 'Série(C100)'), CampoContexto("C100", 8, 'Chave de Acesso(C100)'), CampoContexto("C100", 1, 'Indicador de Operação(C100)'), CampoContexto("C100", 2, 'Indicador de Emissão(C100)'),),
    ),
    "C190": LayoutRegistro(
        codigo="C190",
        nome_aba='C190 - Analítico',
        cabecalhos=('C190 - Fixo',
 'CST de ICMS',
 'CFOP',
 'Alíquota de Icms',
 'Valor da Operação',
 'Base de Icms',
 'Valor de Icms',
 'Base de Icms ST',
 'Valor de Icms ST',
 'Valor Redução de Base de Icms',
 'Valor de IPI',
 'Código de Observações'),
        contexto=(CampoContexto("C100", 3, 'Participante(C100)'), CampoContexto("C100", 7, 'Número da Nota(C100)'), CampoContexto("C100", 4, 'Modelo(C100)'), CampoContexto("C100", 6, 'Série(C100)'), CampoContexto("C100", 1, 'Indicador de Operação(C100)'), CampoContexto("C100", 2, 'Indicador de Emissão(C100)'), CampoContexto("C100", 8, 'Chave de Acesso(C100)'),),
    ),
    "C195": LayoutRegistro(
        codigo="C195",
        nome_aba='C195',
        cabecalhos=('C195', 'COD_OBS', 'TXT_COMPL'),
        contexto=(CampoContexto("C100", 3, 'Participante(C100)'), CampoContexto("C100", 7, 'Número da Nota(C100)'), CampoContexto("C100", 4, 'Modelo(C100)'), CampoContexto("C100", 6, 'Série(C100)'), CampoContexto("C100", 1, 'Indicador de Operação(C100)'), CampoContexto("C100", 2, 'Indicador de Emissão(C100)'),),
    ),
    "C197": LayoutRegistro(
        codigo="C197",
        nome_aba='C197',
        cabecalhos=('C197', 'COD_AJ', 'DESCR_COMPL_AJ', 'COD_ITEM', 'VL_BC_ICMS', 'ALIQ_ICMS', 'VL_ICMS', 'VL_OUTROS'),
        contexto=(CampoContexto("C100", 3, 'Participante(C100)'), CampoContexto("C100", 7, 'Número da Nota(C100)'), CampoContexto("C100", 4, 'Modelo(C100)'), CampoContexto("C100", 6, 'Série(C100)'), CampoContexto("C100", 1, 'Indicador de Operação(C100)'), CampoContexto("C100", 2, 'Indicador de Emissão(C100)'), CampoContexto("C195", 1, 'COD_OBS(C195)'),),
    ),
    "C990": LayoutRegistro(
        codigo="C990",
        nome_aba='C990',
        cabecalhos=('C990', 'QTD_LIN_C'),
        contexto=(),
    ),
    "D001": LayoutRegistro(
        codigo="D001",
        nome_aba='D001',
        cabecalhos=('D001', 'IND_MOV'),
        contexto=(),
    ),
    "D100": LayoutRegistro(
        codigo="D100",
        nome_aba='D100 - Fretes',
        cabecalhos=('D100 - Fixo',
 'Indicador de Operação',
 'Indicador de Emissão',
 'Participante',
 'Modelo',
 'Situação',
 'Série',
 'Sub-Série',
 'Numero',
 'Chave',
 'Data de Emissão',
 'Data de Entrada/Saída',
 'Tipo de CTE',
 'Chave de CTE Ref',
 'Valor',
 'Desconto',
 'Tipo de Frete',
 'Valor do Serviço',
 'BC de ICMS',
 'Valor de ICMS',
 'Valor Não tributado de ICMS',
 'Informação Complementar',
 'Conta Contábil',
 'Cód. município origem',
 'Cód. município destino'),
        contexto=(),
    ),
    "D190": LayoutRegistro(
        codigo="D190",
        nome_aba='D190 - Analítico',
        cabecalhos=('D190 - Fixo',
 'CST de ICMS',
 'CFOP',
 'Alíquota de Icms',
 'Valor da Operação',
 'Base de Icms',
 'Valor de Icms',
 'Valor Não  Tributado de Icms',
 'Código de Observações'),
        contexto=(CampoContexto("D100", 3, 'Participante(D100)'), CampoContexto("D100", 8, 'Número do CTE(D100)'), CampoContexto("D100", 6, 'Série(D100)'), CampoContexto("D100", 1, 'Indicador de Operação(D100)'), CampoContexto("D100", 2, 'Indicador de Emissão(D100)'),),
    ),
    "D990": LayoutRegistro(
        codigo="D990",
        nome_aba='D990',
        cabecalhos=('D990', 'QTD_LIN_D'),
        contexto=(),
    ),
    "E001": LayoutRegistro(
        codigo="E001",
        nome_aba='E001',
        cabecalhos=('E001', 'IND_MOV'),
        contexto=(),
    ),
    "E100": LayoutRegistro(
        codigo="E100",
        nome_aba='E100',
        cabecalhos=('E100', 'DT_INI', 'DT_FIN'),
        contexto=(),
    ),
    "E110": LayoutRegistro(
        codigo="E110",
        nome_aba='E110',
        cabecalhos=('E110',
 'VL_TOT_DEBITOS',
 'VL_AJ_DEBITOS',
 'VL_TOT_AJ_DEBITOS',
 'VL_ESTORNOS_CRED',
 'VL_TOT_CREDITOS',
 'VL_AJ_CREDITOS',
 'VL_TOT_AJ_CREDITOS',
 'VL_ESTORNOS_DEB',
 'VL_SLD_CREDOR_ANT',
 'VL_SLD_APURADO',
 'VL_TOT_DED',
 'VL_ICMS_RECOLHER',
 'VL_SLD_CREDOR_TRANSPORTAR',
 'DEB_ESP'),
        contexto=(CampoContexto("E100", 1, 'DT_INI(E100)'), CampoContexto("E100", 2, 'DT_FIN(E100)'),),
    ),
    "E111": LayoutRegistro(
        codigo="E111",
        nome_aba='E111',
        cabecalhos=('E111', 'COD_AJ_APUR', 'DESCR_COMPL_AJ', 'VL_AJ_APUR'),
        contexto=(CampoContexto("E100", 1, 'DT_INI(E100)'), CampoContexto("E100", 2, 'DT_FIN(E100)'),),
    ),
    "E113": LayoutRegistro(
        codigo="E113",
        nome_aba='E113',
        cabecalhos=('E113', 'COD_PART', 'COD_MOD', 'SER', 'SUB', 'NUM_DOC', 'DT_DOC', 'COD_ITEM', 'VL_AJ_ITEM', 'CHV_DOCe'),
        contexto=(CampoContexto("E100", 1, 'DT_INI(E100)'), CampoContexto("E100", 2, 'DT_FIN(E100)'), CampoContexto("E111", 1, 'COD_AJ_APUR(E111)'), CampoContexto("E111", 2, 'DESCR_COMPL_AJ(E111)'), CampoContexto("E111", 3, 'VL_AJ_APUR(E111)'),),
    ),
    "E116": LayoutRegistro(
        codigo="E116",
        nome_aba='E116',
        cabecalhos=('E116', 'COD_OR', 'VL_OR', 'DT_VCTO', 'COD_REC', 'NUM_PROC', 'IND_PROC', 'PROC', 'TXT_COMPL', 'MES_REF*'),
        contexto=(CampoContexto("E100", 1, 'DT_INI(E100)'), CampoContexto("E100", 2, 'DT_FIN(E100)'),),
    ),
    "E300": LayoutRegistro(
        codigo="E300",
        nome_aba='E300',
        cabecalhos=('E300', 'UF', 'DT_INI', 'DT_FIN'),
        contexto=(),
    ),
    "E310": LayoutRegistro(
        codigo="E310",
        nome_aba='E310',
        cabecalhos=('E310',
 'IND_MOV_FCP_DIFAL',
 'VL_SLD_CRED_ANT_DIFAL',
 'VL_TOT_DEBITOS_DIFAL',
 'VL_OUT_DEB_DIFAL',
 'VL_TOT_CREDITOS_DIFAL',
 'VL_OUT_CRED_DIFAL',
 'VL_SLD_DEV_ANT_DIFAL',
 'VL_DEDUÇÕES_DIFAL',
 'VL_RECOL_DIFAL',
 'VL_SLD_CRED_TRANSPORTAR_DIFAL',
 'DEB_ESP_DIFAL',
 'VL_SLD_CRED_ANT_FCP',
 'VL_TOT_DEB_FCP',
 'VL_OUT_DEB_FCP',
 'VL_TOT_CRED_FCP',
 'VL_OUT_CRED_FCP',
 'VL_SLD_DEV_ANT_FCP',
 'VL_DEDUÇÕES_FCP',
 'VL_RECOL_FCP',
 'VL_SLD_CRED_TRANSPORTAR_FCP',
 'DEB_ESP_FCP'),
        contexto=(CampoContexto("E300", 1, 'UF(E300)'),),
    ),
    "E316": LayoutRegistro(
        codigo="E316",
        nome_aba='E316',
        cabecalhos=('E316', 'COD_OR', 'VL_OR', 'DT_VCTO', 'COD_REC', 'NUM_PROC', 'IND_PROC', 'PROC', 'TXT_COMPL', 'MES_REF*'),
        contexto=(CampoContexto("E300", 1, 'UF(E300)'),),
    ),
    "E990": LayoutRegistro(
        codigo="E990",
        nome_aba='E990',
        cabecalhos=('E990', 'QTD_LIN_E'),
        contexto=(),
    ),
    "G001": LayoutRegistro(
        codigo="G001",
        nome_aba='G001',
        cabecalhos=('G001', 'IND_MOV'),
        contexto=(),
    ),
    "G990": LayoutRegistro(
        codigo="G990",
        nome_aba='G990',
        cabecalhos=('G990', 'QTD_LIN_G'),
        contexto=(),
    ),
    "H001": LayoutRegistro(
        codigo="H001",
        nome_aba='H001',
        cabecalhos=('H001', 'IND_MOV'),
        contexto=(),
    ),
    "H990": LayoutRegistro(
        codigo="H990",
        nome_aba='H990',
        cabecalhos=('H990', 'QTD_LIN_H'),
        contexto=(),
    ),
    "K001": LayoutRegistro(
        codigo="K001",
        nome_aba='K001',
        cabecalhos=('K001', 'IND_MOV'),
        contexto=(),
    ),
    "K990": LayoutRegistro(
        codigo="K990",
        nome_aba='K990',
        cabecalhos=('K990', 'QTD_LIN_K'),
        contexto=(),
    ),
    "9001": LayoutRegistro(
        codigo="9001",
        nome_aba='9001',
        cabecalhos=('9001', 'IND_MOV'),
        contexto=(),
    ),
    "9900": LayoutRegistro(
        codigo="9900",
        nome_aba='9900',
        cabecalhos=('9900', 'REG_BLC', 'QTD_REG_BLC'),
        contexto=(),
    ),
    "9990": LayoutRegistro(
        codigo="9990",
        nome_aba='9990',
        cabecalhos=('9990', 'QTD_LIN_9'),
        contexto=(),
    ),
    "9999": LayoutRegistro(
        codigo="9999",
        nome_aba='9999',
        cabecalhos=('9999', 'QTD_LIN'),
        contexto=(),
    ),
}


RESETAR_CONTEXTOS_AO_LER: dict[str, tuple[str, ...]] = {
    "0001": ("0200",),
    "C001": ("C100", "C195"),
    "C100": ("C195",),
    "D001": ("D100",),
    "E001": ("E100", "E111", "E300"),
    "E100": ("E111",),
}


def obter_layout(codigo: str) -> LayoutRegistro | None:
    return LAYOUTS_REGISTROS.get(codigo.upper())
